---
swagger: "2.0"
info:
  description: "This API describes the minimum interface that a USS must implement\
    \ to  be part of the USS Network.  This API allows for communication of data \
    \ between USS Instances and from FIMS to a USS regarding new USS Instances."
  version: "v1"
  title: "USS Required API"
  termsOfService: "\nA. No Warranty: THE SUBJECT SOFTWARE IS PROVIDED \"AS IS\" WITHOUT\
    \ ANY WARRANTY OF ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING,\
    \ BUT NOT LIMITED TO, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL CONFORM TO SPECIFICATIONS,\
    \ ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,\
    \ OR FREEDOM FROM INFRINGEMENT, ANY WARRANTY THAT THE SUBJECT SOFTWARE WILL BE\
    \ ERROR FREE, OR ANY WARRANTY THAT DOCUMENTATION, IF PROVIDED, WILL CONFORM TO\
    \ THE SUBJECT SOFTWARE. THIS AGREEMENT DOES NOT, IN ANY MANNER, CONSTITUTE AN\
    \ ENDORSEMENT BY GOVERNMENT AGENCY OR ANY PRIOR RECIPIENT OF ANY RESULTS, RESULTING\
    \ DESIGNS, HARDWARE, SOFTWARE PRODUCTS OR ANY OTHER APPLICATIONS RESULTING FROM\
    \ USE OF THE SUBJECT SOFTWARE. FURTHER, GOVERNMENT AGENCY DISCLAIMS ALL WARRANTIES\
    \ AND LIABILITIES REGARDING THIRD-PARTY SOFTWARE, IF PRESENT IN THE ORIGINAL SOFTWARE,\
    \ AND DISTRIBUTES IT \"AS IS.\"\n\nB. Waiver and Indemnity: RECIPIENT AGREES TO\
    \ WAIVE ANY AND ALL CLAIMS AGAINST THE UNITED STATES GOVERNMENT, ITS CONTRACTORS\
    \ AND SUBCONTRACTORS, AS WELL AS ANY PRIOR RECIPIENT. IF RECIPIENT''S USE OF THE\
    \ SUBJECT SOFTWARE RESULTS IN ANY LIABILITIES, DEMANDS, DAMAGES, EXPENSES OR LOSSES\
    \ ARISING FROM SUCH USE, INCLUDING ANY DAMAGES FROM PRODUCTS BASED ON, OR RESULTING\
    \ FROM, RECIPIENT''S USE OF THE SUBJECT SOFTWARE, RECIPIENT SHALL INDEMNIFY AND\
    \ HOLD HARMLESS THE UNITED STATES GOVERNMENT, ITS CONTRACTORS AND SUBCONTRACTORS,\
    \ AS WELL AS ANY PRIOR RECIPIENT, TO THE EXTENT PERMITTED BY LAW. RECIPIENT''S\
    \ SOLE REMEDY FOR ANY SUCH MATTER SHALL BE THE IMMEDIATE, UNILATERAL TERMINATION\
    \ OF THIS AGREEMENT.\n"
  contact:
    name: "NASA Ames Research Center, Aviation Systems Division"
    url: "https://utm.arc.nasa.gov/"
    email: "joseph.rios@nasa.gov"
  license:
    name: "NASA Open Source Agreement"
    url: "https://ti.arc.nasa.gov/opensource/nosa/"
host: "uss.defined.url"
basePath: "/uss"
schemes:
- "https"
- "wss"
paths:
  /api:
    get:
      tags:
      - "A. Required REST endpoints"
      summary: "API version and other data. Can be used to test whether server is\
        \ up."
      description: "Provides versioning information for the software and API. Can\
        \ be used to determine if service is up."
      operationId: "getVersion"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Version data"
          schema:
            $ref: "#/definitions/Version"
  /alert_messages:
    post:
      tags:
      - "A. Required REST endpoints"
      summary: "Allow other authorized entities to send a message to this USS."
      description: "Allows another USS or FIMS to POST a message to this USS."
      operationId: "postAlertMessage"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "message"
        description: "The message being sent"
        required: true
        schema:
          $ref: "#/definitions/AlertMessage"
      responses:
        201:
          description: "Message data received."
  /uss:
    post:
      tags:
      - "A. Required REST endpoints"
      summary: "Allow USS Discovery Service to send data"
      description: "As per the USS Discovery Service specification, this endpoint\
        \ is for receiving messages about the USS Network from the USS Discovery Service.\
        \  For example, when a new USS Instance is registered, that announcement would\
        \ come to this endpoint."
      operationId: "postUSSDiscoveryMessage"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "message"
        description: "The message being sent"
        required: true
        schema:
          $ref: "#/definitions/UssInstanceMessage"
      responses:
        201:
          description: "Message data received."
  /negotiations:
    post:
      tags:
      - "A. Required REST endpoints"
      summary: "Allow other USSs to submit a negotiation request"
      description: "A POST to the negotiations endpoint is interpretted as a request\
        \ for alteration in an existing operation managed by the receiving USS.  The\
        \ requesting USS supplies a GUFI that references the operation that may be\
        \ altered if the request is granted by the receiving USS."
      operationId: "postNegotiation"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "operation"
        description: "The operation data"
        required: true
        schema:
          $ref: "#/definitions/Operation"
      responses:
        200:
          description: "Negotiation request received, decision provided"
          schema:
            $ref: "#/definitions/NegotiationResponse"
        400:
          description: "Problem with submitted data"
  /operations:
    get:
      tags:
      - "A. Required REST endpoints"
      summary: "Request information regarding Operations"
      description: "Allows querying for Operation data."
      operationId: "getOps"
      produces:
      - "application/json"
      parameters:
      - name: "fields"
        in: "query"
        description: "The specific subset of fields to return. Comma separated list.\
          \ Default will be all fields when this parameter is not provided in the\
          \ query. Duplicate field names not allowed and server may reject query if\
          \ duplicates are provided. If field names are provided that are not part\
          \ of the request model, the server may either reject the query or ignore\
          \ the improper fields. Maximum 20 field values supported. If more than 20\
          \ fields are required, then this parameter should not be used so that all\
          \ fields are returned."
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "csv"
        maxItems: 20
        minItems: 1
        uniqueItems: true
      - name: "sort"
        in: "query"
        description: "A valid field name to use for sorting records. If multiple fields\
          \ are provided, the sorting is based on the ordered priorty of that list."
        required: false
        type: "string"
        default: "time_submitted"
      - name: "sort_increasing"
        in: "query"
        description: "For optional use with the 'sort' parameter. If 'sort' is not\
          \ provided, then 'sort_increasing' will be ignored. Boolean value.  If multiple\
          \ fields are provided in the 'sort' paramenter, this boolean value will\
          \ apply to all of them."
        required: false
        type: "boolean"
        default: true
      - name: "limit"
        in: "query"
        description: "The maximum number or records to return."
        required: false
        type: "integer"
        default: 10
        maximum: 100
        minimum: 1
        format: "int32"
      - name: "offset"
        in: "query"
        description: "The index from which to begin the list of returned records."
        required: false
        type: "integer"
        default: 0
        format: "int32"
      responses:
        200:
          description: "Successful data request. Response includes requested data."
          schema:
            $ref: "#/definitions/Operation"
        400:
          description: "Bad request. Typically validation error. Fix your request\
            \ and retry."
        429:
          description: "Too many recent requests from you. Wait to make further queries."
    post:
      tags:
      - "A. Required REST endpoints"
      summary: "Allow other USSs to submit their UAS Operations."
      description: "A POST to the operations endpoint allows for sharing of operational\
        \ data between USSs.  This is the primary mechanism by which USSs become aware\
        \ of each others' UAS operations.<br/><br/>\nA USS is required to share operation\
        \ data with other USSs that may have interacting UAS Operations.  This potential\
        \ interaction is known through the data provided via the USS Service Discovery\
        \ mechanism (see https://app.swaggerhub.com/apis/utm/ussdiscovery/v2)."
      operationId: "postOp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "operation"
        description: "The operation data"
        required: true
        schema:
          $ref: "#/definitions/Operation"
      responses:
        201:
          description: "Operation data received."
        400:
          description: "Bad request. Typically validation error. Fix your request\
            \ and retry."
        429:
          description: "Too many recent requests from you. Wait to make further submissions."
    put:
      tags:
      - "A. Required REST endpoints"
      summary: "Submit updates to a previously communicated UAS Operation."
      description: "Allows for other USSs to update a previous plan submission."
      operationId: "putOp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "operation"
        description: "Operational plan with the following properties:\n  1. Contains\
          \ a valid uss_operation_id.\n  2. time_available_end value that is in the\
          \ future.\n  3. No date-time fields that are in the past are modified.\n\
          \  4. Other rules for a USS Operation POST are satisfied.\n"
        required: true
        schema:
          $ref: "#/definitions/Operation"
      responses:
        200:
          description: "Successful data request. Response includes requested data."
          schema:
            $ref: "#/definitions/Operation"
        400:
          description: "Bad request. Typically validation error. Fix your request\
            \ and retry."
        429:
          description: "Too many recent requests from you. Wait to make further queries."
definitions:
  NegotiationResponse:
    type: "object"
    properties:
      requested_gufi:
        type: "string"
        format: "uuid"
      response:
        type: "string"
        enum:
        - "GRANTED"
        - "REFUSED"
      reason_for_refusal:
        type: "string"
        enum:
        - "A"
        - "B"
        - "C"
  Version:
    type: "object"
    properties:
      title:
        type: "string"
        description: "Title of the API"
      version:
        type: "string"
        description: "Version number for the API"
      build_time:
        type: "string"
        description: "Time of the latest build"
      api_documentation:
        type: "string"
        description: "URL for API Documentation"
  AlertMessage:
    type: "object"
    properties:
      message_id:
        type: "string"
        format: "uuid"
        description: "A UUID assigned to this message by the originator"
        minLength: 36
        maxLength: 36
      origin:
        type: "string"
        description: "The user or process that generated this message"
        enum:
        - "FIMS"
        - "USS"
      originator_id:
        type: "string"
        description: "A name identifying the originator of this message."
        maxLength: 100
      gufi:
        type: "string"
        format: "uuid"
        description: "The GUFI for the operation referenced in this message."
        minLength: 36
        maxLength: 36
      sent_time:
        type: "string"
        format: "date-time"
        example: "2015-08-20T14:11:57.345Z"
        description: "Time the message was generated by the origin.  Uses the ISO\
          \ 8601 format conforming to pattern: YYYY-MM-DDThh:mm:ss.sssZ.  Seconds\
          \ may have up to millisecond accuracy (three positions after decimal). \
          \ The 'Z' implies UTC times and is the only timezone accepted.\""
      severity:
        $ref: "#/definitions/severity"
      alert_type:
        type: "string"
        description: "The type of alert message. An enum to constrain messages and\
          \ allow better interoperability."
        enum:
        - "UNPLANNED_LANDING"
        - "UNCONTROLLED_LANDING"
        - "OPERATION_NON_CONFORMING"
        - "OPERATION_ROGUE"
        - "OPERATION_CONFORMING"
        - "OPERATION_CLOSED"
        - "CONTINGENCY_INITIATED"
        - "OTHER_SEE_FREE_TEXT"
      last_known_position:
        $ref: "#/definitions/Position"
      contingency:
        $ref: "#/definitions/Contingency"
      metadata:
        type: "string"
        description: "Reserved field."
      free_text:
        type: "string"
        description: "Any additional information. Note that this is for human consumption.\
          \ All time critical elements should be captured in the other data fields\
          \ for easier consumption by other automated systems."
        maxLength: 1000
    description: "An alert message. Used to make other stakeholders aware about an\
      \ issue with a specific operation."
    example:
      gufi: "00000000-0000-4444-8888-000000000000"
      category: "AlertMessage"
      origin: "FIMS"
      sent_time: "2016-10-04T09:15:42.727Z"
      alert_message: "OPERATIONS"
      alert_severity: "WARNING"
      alert_text: "UA_LEAVING_DEFINED_VOLUME"
      free_text: " reason=RogueNearby, reasonDetail=nearby operation 86250f05-d89c-40cf-b932-aa8d10a426a2\
        \ in state U is lateral distance 711.45 feet and vertical danger zone envelope\
        \ 600 feet; This alert message valid for the next 30 seconds (far lateral/far\
        \ altitude), vehicleType=FixedWing vehicleModelName=Silent Falcon, longLat=-119.87933795058\
        \ 39.69702548394, alt_gps_wgs84_ft=5187.3645438621, track_ground_speed_kn=0.77703200548507,\
        \ track_magnet ic_north_deg=null"
  severity:
    type: "string"
    enum:
    - "EMERGENCY"
    - "ALERT"
    - "CRITICAL"
    - "WARNING"
    - "NOTICE"
    - "INFORMATIONAL"
  Position:
    type: "object"
    required:
    - "altitude_gps_wgs84_ft"
    - "altitude_num_gps_satellites"
    - "gufi"
    - "hdop_gps"
    - "location"
    - "time_measured"
    - "time_sent"
    - "track_ground_speed_kn"
    - "track_true_north_deg"
    - "vdop_gps"
    properties:
      air_speed_source:
        type: "string"
        description: "Required if air_speed_track_kn is submitted. No requirements\
          \ yet on the values here, but suggestions include ESTIMATED or MEASURED."
        maxLength: 100
      air_speed_track_kn:
        type: "number"
        format: "double"
        description: "Air speed in relation to the direction of travel of the aircraft.\
          \ Value may be negative."
      altitude_gps_wgs84_ft:
        type: "number"
        format: "double"
        description: "The altitude as measured via a GPS device on the aircraft. Units\
          \ in feet using the WGS84 reference system."
      altitude_num_gps_satellites:
        type: "integer"
        format: "int32"
        description: "Number of satellites used in calculating the altitude_gps_wgs84_ft."
        minimum: 0
        exclusiveMinimum: false
      enroute_positions_id:
        type: "string"
        format: "uuid"
        description: "Each position will be assigned a UUIDv4 by the FIMS"
        minLength: 36
        maxLength: 36
      gufi:
        type: "string"
        format: "uuid"
        description: "Each operation has an GUFI assigned upon submission. Required\
          \ upon POSTing a new position. It is a JSON string, but conforms to the\
          \ UUID version 4 specification"
        minLength: 36
        maxLength: 36
      hdop_gps:
        type: "number"
        format: "double"
        description: "The horizontal dilution of precision as provided by the onboard\
          \ GPS."
        minimum: 0.0
      location:
        $ref: "#/definitions/Point"
      time_measured:
        type: "string"
        format: "date-time"
        example: "2015-08-20T14:11:56.118Z"
        description: "The time the position was measured. Likely the time provided\
          \ with the GPS position reading.  Time must be before time received at FIMS\
          \ based on FIMS system time.  Uses the ISO 8601 format conforming to pattern:\
          \ YYYY-MM-DDThh:mm:ss.sssZ.  Seconds may have up to millisecond accuracy\
          \ (three positions after decimal).  The 'Z' implies UTC times and is the\
          \ only timezone accepted."
      time_received:
        type: "string"
        format: "date-time"
        example: "2015-08-20T14:11:57.345Z"
        description: "Not required for submission, assigned by FIMS. The time the\
          \ position was received by FIMS based on FIMS system time.  Uses the ISO\
          \ 8601 format conforming to pattern: YYYY-MM-DDThh:mm:ss.sssZ.  Seconds\
          \ may have up to millisecond accuracy (three positions after decimal). \
          \ The 'Z' implies UTC times and is the only timezone accepted."
      time_sent:
        type: "string"
        format: "date-time"
        example: "2015-08-20T14:11:57.968Z"
        description: "The time the position was sent by the USS to FIMS as measured\
          \ by USS system time.  Time must be before time received at FIMS based on\
          \ FIMS system time.  Uses the ISO 8601 format conforming to pattern: YYYY-MM-DDThh:mm:ss.sssZ.\
          \  Seconds may have up to millisecond accuracy (three positions after decimal).\
          \  The 'Z' implies UTC times and is the only timezone accepted."
      track_ground_speed_kn:
        type: "number"
        format: "double"
        description: "Ground speed int the direction of travel. Value must be >= 0.0.\
          \ In knots."
        minimum: 0.0
        exclusiveMinimum: false
      track_magnetic_north_deg:
        type: "number"
        format: "double"
        description: "The direction of travel relative to magnetic north in degrees.\
          \ Value must be >= 0.0 and < 360.0."
        minimum: 0.0
        maximum: 360.0
        exclusiveMinimum: false
        exclusiveMaximum: true
      track_true_north_deg:
        type: "number"
        format: "double"
        description: "The direction of travel relative to true north in degrees. Value\
          \ must be >= 0.0 and < 360.0."
        minimum: 0.0
        maximum: 360.0
        exclusiveMinimum: false
        exclusiveMaximum: true
      user_id:
        type: "string"
        description: "Not required for submission. This field is populated based on\
          \ the provided credentials in the HTTPS header."
      vdop_gps:
        type: "number"
        format: "double"
        description: "The vertical dilultion of precision as provided by the onboard\
          \ GPS."
        minimum: 0.0
    example:
      altitude_gps_wgs84_ft: 1111.111
      altitude_num_gps_satellites: 22
      air_speed_source: "MEASURED"
      gufi: "00000000-0000-4444-8888-000000000000"
      hdop_gps: 77.7
      time_measured: "2016-10-04T09:15:40.727Z"
      time_sent: "2016-10-04T09:15:40.727Z"
      time_received: "2016-10-04T09:15:42.727Z"
      track_ground_speed_kn: 33.33
      track_true_north_deg: 235.027287562664
      track_magnetic_north_deg: 237.123456789123
      vdop_gps: 88.8
      location:
        type: "Point"
        coordinates:
        - -122.05635935068132
        - 37.41436490284069
  Point:
    type: "object"
    properties:
      type:
        type: "string"
        description: "The type of Geometry. In this case, must be 'Point' per GeoJSON\
          \ spec.\n"
        enum:
        - "Point"
      coordinates:
        $ref: "#/definitions/Position"
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.2"
    description: "GeoJSon Point, limited to 2D."
  Contingency:
    type: "object"
    properties:
      contingency_id:
        type: "number"
        format: "integer"
        description: "A positive integer unique amongst the set of Contingencies for\
          \ this operation. The integers may be ordered by some scheme, but this is\
          \ not required."
        minimum: 1
        maximum: 1000
      contingency_type:
        type: "string"
        enum:
        - "LANDING"
        - "LOITERING"
        - "RETURN_TO_BASE"
      contingency_point:
        $ref: "#/definitions/Point"
      loiter_altitude_wgs84_ft:
        type: "number"
        format: "double"
        description: "The altitude for this contingency. Relevant and required for\
          \ the LOITERING contingency_type, ignored for all other types. In WGS84\
          \ reference system using feet as units."
      loiter_radius_ft:
        type: "number"
        format: "double"
        description: "The radius of airspace used in loitering for this contingency.\
          \ Relevant and required for the LOITERING contingency_type, ignored for\
          \ all other types. Using feet as units."
      relative_preference:
        type: "number"
        format: "double"
        description: "Optional numerical value that can be used in ranking the preference\
          \ of this Contingency versus any other within the set of Contingency for\
          \ this operation. This may be thought of as a ranking of the potential landing\
          \ sites with all other factors being held equal, though dynamic conditions\
          \ will likely play a role in adjusting this ranking in real time by the\
          \ USS or Operator.  For example, one Contingency may be significantly further\
          \ from the operation at a given time and, thus, would be less preferred\
          \ than it might be otherwise. Further interpretation of this field is left\
          \ to the operator and USS. "
        minimum: 0.0
      contingency_location_description:
        type: "string"
        description: "Optional description of the contingency location."
        maxLength: 1000
      valid_time_begin:
        type: "string"
        format: "date-time"
        example: "2015-08-20T14:31:56.118Z"
        description: "Optional. Time that this location is expected to be first available.\
          \ For example, if an operation begins at 1100, but this location is not\
          \ available until 1105 at the earliest, then this field could indicate that\
          \ fact. Uses the ISO 8601 format conforming to pattern: YYYY-MM-DDThh:mm:ss.sssZ.\
          \  Seconds may have up to millisecond accuracy (three positions after decimal).\
          \  The 'Z' implies UTC times and is the only timezone accepted."
      valid_time_end:
        type: "string"
        format: "date-time"
        example: "2015-08-20T14:31:56.118Z"
        description: "Optional. Time that this location is expected to become unavailable.\
          \ For example, if an operation begins at 1100, but this location becomes\
          \ closed for some reason at 1105, then this field could indicate that fact.\
          \ Uses the ISO 8601 format conforming to pattern: YYYY-MM-DDThh:mm:ss.sssZ.\
          \  Seconds may have up to millisecond accuracy (three positions after decimal).\
          \  The 'Z' implies UTC times and is the only timezone accepted."
  UssInstanceMessage:
    type: "object"
    properties:
      a:
        type: "string"
    description: "A message."
  Operation:
    type: "object"
    required:
    - "controller_location"
    - "gufi"
    - "operation_volumes"
    - "primary_contact_name"
    - "primary_contact_phone"
    - "registration"
    properties:
      gufi:
        type: "string"
        format: "uuid"
        description: "Created and assigned by originating USS. Validated as UUID version\
          \ 4 specification."
        minLength: 36
        maxLength: 36
      submit_time:
        type: "string"
        format: "date-time"
        example: "2015-08-20T14:11:56.118Z"
        description: "Time the operation submission was received by USS. Uses the\
          \ ISO 8601 format conforming to pattern: YYYY-MM-DDThh:mm:ss.sssZ. Seconds\
          \ may have up to millisecond accuracy (three positions after decimal). \
          \ The 'Z' implies UTC times and is the only timezone accepted."
      decision_time:
        type: "string"
        format: "date-time"
        example: "2015-08-20T14:11:56.118Z"
        description: "A timestamp set by the USS any time the state of the operation\
          \ is updated, for example when the flight goes from ACCEPTED to ACTIVATED.\
          \  Uses the ISO 8601 format conforming to pattern: YYYY-MM-DDThh:mm:ss.sssZ.\
          \  Seconds may have up to millisecond accuracy (three positions after decimal).\
          \  The 'Z' implies UTC times and is the only timezone accepted."
      aircraft_comments:
        type: "string"
        description: "Informative text about the aircraft. Not used by the UTM System.\
          \ Only for human stakeholders."
        maxLength: 1000
        default: "NOT PROVIDED"
      flight_comments:
        type: "string"
        description: "Informative text about the operation. Not used by the UTM System.\
          \ Only for human stakeholders."
        maxLength: 1000
        default: "NOT PROVIDED"
      geography_description:
        type: "string"
        description: "Informative text about the operational geography. Not used by\
          \ the UTM System. Only for human stakeholders."
        maxLength: 1000
        default: "NOT PROVIDED"
      registration:
        type: "array"
        description: "The registration ID of the vehicle flying this operation. This\
          \ registration value is provided to operators by a vehicle registrar. Validated\
          \ as a non-null string. Array due to possiblity of multi-vehicle operation."
        items:
          type: "string"
          maxLength: 1000
        minItems: 1
      performance_authorization:
        type: "string"
        format: "uuid"
        description: "TBD"
        minLength: 36
        maxLength: 36
      flight_number:
        type: "string"
        description: "Optional. For use by USS for identification purposes."
        maxLength: 100
      user_id:
        type: "string"
        description: "This field is populated based on the provided credentials."
      created_by:
        type: "string"
        description: "The user that created the operation."
        maxLength: 100
      primary_contact_name:
        type: "string"
        description: "Not currently checked for validity, but clients should endeavor\
          \ to provide useful, appropriate information in these fields. These values\
          \ should represent the contact that should be used in case of an issue with\
          \ the operation before, during, or after that operation."
        maxLength: 100
      primary_contact_phone:
        type: "string"
        format: "phone"
        maxLength: 100
      primary_contact_email:
        type: "string"
        format: "email"
        maxLength: 100
      extra_contact_info:
        type: "string"
        description: "Any additional contact information that may be useful (hours\
          \ of availability, fax number, communication limitations, etc.)."
        maxLength: 1000
        default: "NOT PROVIDED"
      state:
        type: "string"
        description: "The current state of the operation.  Must be maintained by the\
          \ USS.\n"
        minLength: 5
        maxLength: 13
        enum:
        - "ACCEPTED"
        - "ACTIVATED"
        - "CLOSED"
        - "NONCONFORMING"
        - "ROGUE"
      controller_location:
        $ref: "#/definitions/Point"
      gcs_location:
        $ref: "#/definitions/Point"
      contingency_locations:
        type: "array"
        description: "An array of ContingencyLocations wherein this operation may\
          \ land if needed/required during operation. Aids in planning and communication\
          \ during the execution of a contingency."
        items:
          $ref: "#/definitions/Contingency"
      faa_rule:
        type: "string"
        description: "PART_107: The operation follows FAA rule 107. If USS notifies\
          \ FIMS about this class of operations,\nFIMS will reply that authorization\
          \ is not required. (For TCL2nc FIMS will always accept the operation.)\n\
          \nPART_107X:  In general, operations are 107X if they are doing something\
          \ outside the 107 rule that would require\na waiver under 107.\n\nPART_101E:\
          \ This class of operations could be hobbyists being friendly with other\
          \ users by announcing their intent.\n(For TCL2nc, FIMS will reply with inform\
          \ message \"authorization not required\" and accept the operation. For TCL2nc\
          \ FIMS does not check\nwhether the operation is in a preauthorized area.)\
          \ In the future, a better response for 101E is\n\"Notification received\"\
          \ if within 5 statute miles of an airport, and \"Notification not required\"\
          \ if not within 5 miles.\n\nOTHER: Placeholder for other types of operations.\n"
        enum:
        - "PART_107"
        - "PART_107X"
        - "PART_101E"
        - "OTHER"
        default: "PART_107"
      priority_op:
        type: "boolean"
        description: "If true this operation is managed as a priority operation. Only\
          \ FIMS or a USS with the public safety role may set this field to true."
        default: false
      operation_volumes:
        type: "array"
        description: "The actual geographical information for the operation.  Maximum\
          \ array length of 12 currently allowed."
        items:
          $ref: "#/definitions/OperationVolume"
      metadata:
        type: "string"
        description: "Reserved field."
    example:
      gufi: "00000000-0000-4444-8888-000000000000"
      submit_time: "2016-10-04T09:15:40.727Z"
      decision_time: "2016-10-04T09:15:40.727Z"
      aircraft_comments: "Comments about the aircraft"
      flight_comments: "Comments about the flight"
      flight_geography_description: "A description of the geography"
      registration: "00000000-0000-4444-8888-000000000000"
      flight_number: "Flight number"
      user_id: "fimsUser"
      created_by: "fimsUser"
      primary_contact_name: "Jane Pilot"
      primary_contact_phone: "XXX-XXX-XXXX"
      primary_contact_email: "pilotjane@janepilot.com"
      extra_contact_info: "Fax: XXX-XXX-XXXX"
      state: "A"
      controller_location:
        type: "Point"
        coordinates:
        - -122.048589
        - 37.414869
      gcs_location:
        type: "Point"
        coordinates:
        - -122.048589
        - 37.414869
      operation_volumes:
      - ordinal: 1
        near_structure: false
        effective_time_begin: "2017-10-04T09:15:40.727Z"
        effective_time_end: "2017-10-04T09:25:40.727Z"
        actual_time_end: "2017-10-04T09:25:40.727Z"
        conformance_time_begin: "2017-10-04T09:14:40.727Z"
        conformance_time_end: "2017-10-04T09:26:40.727Z"
        min_altitude_wgs84_ft: 0.0
        max_altitude_wgs84_ft: 300.0
        conform_min_altitude_wgs84_ft: 0.0
        conform_max_altitude_wgs84_ft: 400.0
        flight_geography:
          type: "Polygon"
          coordinates:
          - - - -122.062176579
              - 37.40968041145
            - - -122.05187056889
              - 37.41786527236
            - - -122.03732647634
              - 37.41786440108
            - - -122.062176579
              - 37.40968041145
        conformance_geography:
          type: "Polygon"
          coordinates:
          - - - -122.06382530000002
              - 37.4090697
            - - -122.05094253233
              - 37.4193006277
            - - -122.03276206976
              - 37.41929920176
            - - -122.06382530000002
              - 37.4090697
        beyond_visual_line_of_sight: false
  OperationVolume:
    type: "object"
    required:
    - "beyond_visual_line_of_sight"
    - "effective_time_begin"
    - "effective_time_end"
    - "max_altitude_wgs84_ft"
    - "min_altitude_wgs84_ft"
    - "operation_geography"
    - "ordinal"
    properties:
      ordinal:
        type: "integer"
        description: "This integer represents the ordering of the operation volume\
          \ within the set of operation volumes. Need not be consecutive integers."
      near_structure:
        type: "boolean"
        description: "Is this operation volume within 400' of a structure?"
        default: false
      effective_time_begin:
        type: "string"
        format: "date-time"
        example: "2015-08-20T14:11:56.118Z"
        description: "Earliest time the operation will use the operation volume. \
          \ Uses the ISO 8601 format conforming to pattern: YYYY-MM-DDThh:mm:ss.sssZ.\
          \  Seconds may have up to millisecond accuracy (three positions after decimal).\
          \  The 'Z' implies UTC times and is the only timezone accepted."
      effective_time_end:
        type: "string"
        format: "date-time"
        example: "2015-08-20T15:11:56.118Z"
        description: "Latest time the operation will done with the operation volume.\
          \ It must be greater than effective_time_begin.  Uses the ISO 8601 format\
          \ conforming to pattern: YYYY-MM-DDThh:mm:ss.sssZ.  Seconds may have up\
          \ to millisecond accuracy (three positions after decimal).  The 'Z' implies\
          \ UTC times and is the only timezone accepted."
      actual_time_end:
        type: "string"
        format: "date-time"
        example: "2015-08-20T14:31:56.118Z"
        description: "Time that the operational volume was freed for use by other\
          \ operations.  Should be populated and stored by the USS. Uses the ISO 8601\
          \ format conforming to pattern: YYYY-MM-DDThh:mm:ss.sssZ.  Seconds may have\
          \ up to millisecond accuracy (three positions after decimal).  The 'Z' implies\
          \ UTC times and is the only timezone accepted."
      min_altitude_wgs84_ft:
        type: "number"
        format: "double"
        description: "The minimum altitude for this operation in this operation volume.\
          \ In WGS84 reference system using feet as units."
      max_altitude_wgs84_ft:
        type: "number"
        format: "double"
        description: "The maximum altitude for this operation in this operation volume.\
          \ In WGS84 reference system using feet as units."
      operation_geography:
        $ref: "#/definitions/Polygon"
      beyond_visual_line_of_sight:
        type: "boolean"
        description: "Describes whether the operation volume is beyond the visual\
          \ line of sight of the RPIC."
  Polygon:
    type: "object"
    properties:
      type:
        type: "string"
        description: "The type of Geometry. In this case, must be 'Polygon' per GeoJSON\
          \ spec.\n"
        enum:
        - "Polygon"
      coordinates:
        type: "array"
        items:
          type: "array"
          items:
            $ref: "#/definitions/Position"
    externalDocs:
      url: "https://tools.ietf.org/html/rfc7946#section-3.1.6"
    description: "GeoJSon Polygon. Positions all 2D."
